version: "3.8"

services:
  BackPackDB:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Password1!
      - MYSQL_DATABASE=BackPackDB
    ports:
      - 3310:3306
    restart: always
